version: 1.0
target_condition: deviceId='icarus-jn-002'

container_registries:
  cricarusdev:
    address: cricarusdev.azurecr.io
    password: {{ CRICARUSDEV_PASSWORD }}
    username: {{ CRICARUSDEV_USERNAME }}

modules:
  icarus-edge-detector:
    type: docker
    settings: 
      image: cricarusdev.azurecr.io/icarus-edge-detector:main-010ec9b5625f24d37c57a690034cf83c1880059e
      create_options: "{\"Entrypoint\":[\"/home/docker_user/scripts/start.dev.sh\"]}"
    environment:
      - REMOTE_IP_ADDRESS=10.8.0.2
      - REMOTE_FILE_SENDER_PORT=8443
      - REMOTE_META_DATA_SENDER_PORT=5672
      - REMOTE_META_DATA_SENDER_USERNAME=guest
      - REMOTE_META_DATA_SENDER_PASSWORD=guest
      - META_DATA_SENDER=rabbitmq
