version: 1.0
target_condition: deviceId='icarus-jn-002'

container_registries:
  cricarusdev:
    address: icarus.azurecr.io
    username: {{ CRICARUSDEV_USERNAME }}
    password: {{ CRICARUSDEV_PASSWORD }}

modules:
  icarus-edge-detector:
    type: docker
    settings: 
      image: icarus.azurecr.io/icarus-edge-detector:main-010ec9b5625f24d37c57a690034cf83c1880059e
    environment:
      - REMOTE_IP_ADDRESS=10.8.0.2
      - REMOTE_FILE_SENDER_PORT=8443
      - META_DATA_SENDER=rabbitmq
